PACKAGE_NAME="msdisp"
PACKAGE_VERSION="3.0.3.13"
MAKE[0]="make KVER=$kernelver"
CLEAN="make clean"
BUILT_MODULE_NAME[0]="usbdisp_drm"
BUILT_MODULE_LOCATION[0]="drm/"
DEST_MODULE_LOCATION[0]="/updates/dkms"
BUILT_MODULE_NAME[1]="usbdisp_usb"
BUILT_MODULE_LOCATION[1]="drm/"
DEST_MODULE_LOCATION[1]="/updates/dkms"
AUTOINSTALL="yes"
